### ISSUE TITLE
com.hazelcast.jet.core.metrics.JobMetrics_BatchTest.when_twoDifferentPipelines_then_haveDifferentMetrics[0: mode=member]

### ISSUE THREAD

**Issue by cangencer** [hazelcast/hazelcast-jet#1580] opened 2019-08-27 13:50 UTC
http://jenkins.hazelcast.com/job/jet-oss-pr-builder/864/testReport/junit/com.hazelcast.jet.core.metrics/JobMetrics_BatchTest/when_twoDifferentPipelines_then_haveDifferentMetrics_0__mode_member_/

Stacktrace:
```
java.lang.AssertionError: expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.jet.core.metrics.JobMetrics_BatchTest.assertMetrics(JobMetrics_BatchTest.java:165)
	at com.hazelcast.jet.core.metrics.JobMetrics_BatchTest.when_twoDifferentPipelines_then_haveDifferentMetrics(JobMetrics_BatchTest.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

Standard output:
```
Error Message
expected:<1> but was:<0>
```

**Comment by jbartok** [comment] 2019-08-28 07:20
This issue is caused by the `UnsupportedOperationException` thrown in `CompleteExecutionOperation.JobMetricsRenderer.renderNoValue()`. That method shouldn't throw such an exception (as it turns out it's to be expected that this method will be called sometimes, we just have to ignore it).

The exception has already been removed by https://github.com/hazelcast/hazelcast-jet/pull/1576, so this issue will be fixed too once we merge that in.

**Closed** 2019-08-29 08:16 UTC
Labels: test-failure
