### ISSUE TITLE
com.hazelcast.jet.server.JetCommandLineTest failures

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast-jet#1581] opened 2019-08-28 06:26 UTC
_master_ (commit 2b58883f97fe03b2e4e28b777f1edc1e4e879ccf)

There are 3 test failures in `com.hazelcast.jet.server.JetCommandLineTest`:
* `com.hazelcast.jet.server.JetCommandLineTest.test_resumeJob_byJobId`
* `com.hazelcast.jet.server.JetCommandLineTest.test_restartJob_jobNotRunning`
* `com.hazelcast.jet.server.JetCommandLineTest.test_suspendJob_byJobName`

Failed on ibm-jdk8: http://jenkins.hazelcast.com/job/jet-oss-master-ibm-jdk8/79/

Stacktrace for `com.hazelcast.jet.server.JetCommandLineTest.test_resumeJob_byJobId`:
```
java.lang.AssertionError: jobId=0309-bd25-04c0-0001 expected:<SUSPENDED> but was:<FAILED>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at com.hazelcast.jet.core.JetTestSupport.lambda$assertJobStatusEventually$2(JetTestSupport.java:154)
	at com.hazelcast.jet.core.JetTestSupport$$Lambda$794.000000004001FF70.run(Unknown Source)
	at com.hazelcast.jet.core.JetTestSupport$1.run(JetTestSupport.java:201)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1310)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1327)
	at com.hazelcast.jet.core.JetTestSupport.assertTrueEventually(JetTestSupport.java:162)
	at com.hazelcast.jet.core.JetTestSupport.assertJobStatusEventually(JetTestSupport.java:153)
	at com.hazelcast.jet.core.JetTestSupport.assertJobStatusEventually(JetTestSupport.java:148)
	at com.hazelcast.jet.server.JetCommandLineTest.test_resumeJob_byJobId(JetCommandLineTest.java:277)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.lang.Thread.run(Thread.java:818)
```

Stacktrace for `com.hazelcast.jet.server.JetCommandLineTest.test_restartJob_jobNotRunning`:
```
java.lang.AssertionError: jobId=0309-bd22-0d00-0001 expected:<SUSPENDED> but was:<FAILED>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at com.hazelcast.jet.core.JetTestSupport.lambda$assertJobStatusEventually$2(JetTestSupport.java:154)
	at com.hazelcast.jet.core.JetTestSupport$$Lambda$794.000000004001FF70.run(Unknown Source)
	at com.hazelcast.jet.core.JetTestSupport$1.run(JetTestSupport.java:201)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1310)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1327)
	at com.hazelcast.jet.core.JetTestSupport.assertTrueEventually(JetTestSupport.java:162)
	at com.hazelcast.jet.core.JetTestSupport.assertJobStatusEventually(JetTestSupport.java:153)
	at com.hazelcast.jet.core.JetTestSupport.assertJobStatusEventually(JetTestSupport.java:148)
	at com.hazelcast.jet.server.JetCommandLineTest.test_restartJob_jobNotRunning(JetCommandLineTest.java:348)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.lang.Thread.run(Thread.java:818)
```

Stacktrace for `com.hazelcast.jet.server.JetCommandLineTest.test_suspendJob_byJobName`:
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:349)
	at com.hazelcast.jet.server.JetCommandLine.waitForJobStatus(JetCommandLine.java:515)
	at com.hazelcast.jet.server.JetCommandLine.lambda$suspend$0(JetCommandLine.java:219)
	at com.hazelcast.jet.server.JetCommandLine$$Lambda$978.000000007008A900.accept(Unknown Source)
	at com.hazelcast.jet.server.JetCommandLine.runWithJet(JetCommandLine.java:420)
	at com.hazelcast.jet.server.JetCommandLine.suspend(JetCommandLine.java:214)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at picocli.CommandLine.execute(CommandLine.java:1189)
	at picocli.CommandLine.access$800(CommandLine.java:141)
	at picocli.CommandLine$RunAll.handle(CommandLine.java:1416)
	at picocli.CommandLine$RunAll.handle(CommandLine.java:1376)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1243)
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:1526)
	at com.hazelcast.jet.server.JetCommandLine.runCommandLine(JetCommandLine.java:155)
	at com.hazelcast.jet.server.JetCommandLineTest.run(JetCommandLineTest.java:502)
	at com.hazelcast.jet.server.JetCommandLineTest.test_suspendJob_byJobName(JetCommandLineTest.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.lang.Thread.run(Thread.java:818)
```

Excerpts from the standard output:
```
ERROR MasterJobContext [127.0.0.1]:5701 [e51386ab-0f71-440d-87f6-2286fd3833cc] [3.2-SNAPSHOT] Execution of job 'job-infinite-pipeline', execution 0309-bd22-0d01-0001 failed after 74,699 ms com.hazelcast.core.OperationTimeoutException: MapEventJournalSubscribeOperation got rejected before execution due to not starting within the operation-call-timeout of: 60000 ms. Current time: 2019-08-28 02:07:27.834. Start time: 2019-08-28 02:06:19.857. Total elapsed time: 67978 ms. Invocation{op=com.hazelcast.map.impl.journal.MapEventJournalSubscribeOperation{serviceName='hz:impl:mapService', identityHash=-1560046922, partitionId=56, replicaIndex=0, callId=-1061, invocationTime=1566957979857 (2019-08-28 02:06:19.857), waitTimeout=-1, callTimeout=60000, name=source}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=60000, firstInvocationTimeMs=1566957979857, firstInvocationTime='2019-08-28 02:06:19.857', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 00:00:00.000', target=[127.0.0.1]:5701, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=null}
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.newOperationTimeoutException(InvocationFuture.java:163)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:104)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:79)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:163)
	at com.hazelcast.jet.impl.connector.StreamEventJournalP.init(StreamEventJournalP.java:164)
	at com.hazelcast.jet.core.AbstractProcessor.init(AbstractProcessor.java:83)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.init(ProcessorTasklet.java:231)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$$Lambda$930.000000005402B150.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1268)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService.lambda$submitCooperativeTasklets$4(TaskletExecutionService.java:170)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$$Lambda$929.000000005402AD60.run(Unknown Source)
	at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:440)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService.submitCooperativeTasklets(TaskletExecutionService.java:169)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService.beginExecute(TaskletExecutionService.java:134)
	at com.hazelcast.jet.impl.execution.ExecutionContext.beginExecution(ExecutionContext.java:143)
	at com.hazelcast.jet.impl.JobExecutionService.beginExecution(JobExecutionService.java:342)
	at com.hazelcast.jet.impl.operation.StartExecutionOperation.doRun(StartExecutionOperation.java:44)
	at com.hazelcast.jet.impl.operation.AsyncOperation.run(AsyncOperation.java:50)
	at com.hazelcast.spi.Operation.call(Operation.java:170)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:210)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:199)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:407)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:434)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:648)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:633)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:592)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:256)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:61)
	at com.hazelcast.jet.impl.MasterContext.invokeOnParticipant(MasterContext.java:260)
	at com.hazelcast.jet.impl.MasterContext.invokeOnParticipants(MasterContext.java:244)
	at com.hazelcast.jet.impl.MasterJobContext.invokeStartExecution(MasterJobContext.java:453)
	at com.hazelcast.jet.impl.MasterJobContext.onInitStepCompleted(MasterJobContext.java:429)
	at com.hazelcast.jet.impl.MasterJobContext$$Lambda$810.000000006002AE20.accept(Unknown Source)
	at com.hazelcast.jet.impl.MasterContext.lambda$invokeOnParticipant$1(MasterContext.java:278)
	at com.hazelcast.jet.impl.MasterContext$$Lambda$897.000000004408C2A0.accept(Unknown Source)
	at com.hazelcast.jet.impl.util.ImdgUtil$5.onResponse(ImdgUtil.java:410)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:256)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:818)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:126)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:251)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:818)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
```

If it will show that cause of that failures is different feel free to split this issue into more issues.

**Comment by viliam-durina** [comment] 2019-08-28 11:32
Looks like something bad happened to the cluster and it was stuck. Maybe it's related to https://github.com/hazelcast/hazelcast/issues/13498, but can't tell because the member logs aren't in the test output, only the operation timeout for `MapEventJournalSubscribeOperation`.

**Comment by cangencer** [comment] 2019-09-11 08:40
Closing this as it can't be reproduced and we don't have logs. Should be reopen if it occurs again.

**Closed by cangencer** 2019-09-11 08:40 UTC
Labels: test-failure
