### ISSUE TITLE
BackpressureTest intermittently fails due to timeout

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast-jet#1357] opened 2019-04-08 13:18 UTC
`BackpressureTest.testBackpressure` intermittently fails due to 300s timeout. However when I try to play a little bit with that it shows that it does not freeze out, it just takes longer time - around 350s. What is suspicious here is the reason why this test usually takes around 15s but sometimes takes much longer.

It is reproducible on our Jenkins with OracleJDK 8. Once when https://github.com/hazelcast/hazelcast-jet/pull/1350 will be merged it can be simply executed and reproduced (by unignoring `BackpressureTest`).

**Comment by viliam-durina** [comment] 2019-04-08 14:04
It fails on Windows due to the much longer actual sleeping time of parkNanos. Are you on Windows?

**Comment by olukas** [comment] 2019-04-08 14:13
I am not able reproduce it locally on my linux machine but it is failing on our `lab` machine which is linux.

**Comment by mtopolnik** [comment] 2019-05-27 06:41
The way the processor logic is written here:
```private boolean isHiccuping() {
    if (hiccupDeadline != 0) {
        if (System.nanoTime() < hiccupDeadline) {
            return true;
        }
        System.out.println("==== Resume");
        hiccupDeadline = 0;
        updateNextHiccupTime();
    }
    if (System.nanoTime() >= nextHiccupTime) {
        final long hiccupDuration = MILLISECONDS.toNanos(301)
                + ThreadLocalRandom.current().nextLong(MILLISECONDS.toNanos(570));
        hiccupDeadline = System.nanoTime() + hiccupDuration;
        System.out.println("==== Hiccup " + NANOSECONDS.toMillis(hiccupDuration) + " ms");
    }
    return false;
}
```
means that, if `tryProcess` is called at intervals greater than ~1 second, the processor may never exit the hiccup phase. Maybe that kind of thing actually happens in the test environment.

**Comment by mtopolnik** [comment] 2019-05-28 06:24
Timeout was caused by large CPUs in the build environment because the test was set to process a fixed amount of data per available core, but the actual processing is done all on a single tasklet.

Fixed by capping local parallelism to 8.

**Closed by mtopolnik** 2019-05-28 06:24 UTC
Labels: test-failure
