### ISSUE TITLE
StartExecutionOperation invocation failed after node leaving cluster

### ISSUE THREAD

**Issue by martinkrc** [hazelcast/hazelcast-jet#1572] opened 2019-08-26 14:29 UTC
Sometimes jobs don't recover after nodes leave the cluster, failing with an exception similar to this one:

`
2019-08-26 14:42:31.593  WARN 19040 --- [.async.thread-1] com.hazelcast.jet.impl.MasterContext       : [localhost]:6701 [OurApplication] [0.7.2] Execution of job 'streamingJob', execution 21fd-bd1e-ddeb-d330 failed after 166 715 ms

com.hazelcast.core.OperationTimeoutException: StartExecutionOperation invocation failed to complete due to operation-heartbeat-timeout. Current time: 2019-08-26 14:42:20.813. Start time: 2019-08-26 14:39:44.989. Total elapsed time: 155824 ms. Last operation heartbeat: 2019-08-26 14:41:20.306. Last operation heartbeat from member: 2019-08-26 14:41:20.306. Invocation{op=com.hazelcast.jet.impl.operation.StartExecutionOperation{serviceName='hz:impl:jetService', identityHash=689956290, partitionId=-1, replicaIndex=0, callId=-5928, invocationTime=1566823184989 (2019-08-26 14:39:44.989), waitTimeout=-1, callTimeout=60000}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=60000, firstInvocationTimeMs=1566823184989, firstInvocationTime='2019-08-26 14:39:44.989', lastHeartbeatMillis=1566823280306, lastHeartbeatTime='2019-08-26 14:41:20.306', target=[localhost]:6704, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=Connection[id=3, /127.0.0.1:6701->/127.0.0.1:5417, endpoint=[localhost]:6704, alive=true, type=MEMBER]}
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.newOperationTimeoutException(InvocationFuture.java:164) ~[hazelcast-jet-0.7.2.jar:0.7.2]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:106) ~[hazelcast-jet-0.7.2.jar:0.7.2]
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:250) ~[hazelcast-jet-0.7.2.jar:0.7.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_172]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_172]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_172]
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64) ~[hazelcast-jet-0.7.2.jar:0.7.2]
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80) ~[hazelcast-jet-0.7.2.jar:0.7.2]
`

Steps to reproduce in our case:
1) Start 4 nodes
2) Start a couple of long-term streaming jobs (all the jobs have autoScaling=true and splitBrainProtectionEnabled=false)
3) Freeze node 3 and 4 using Resource Monitor app ("Suspend Process")
=> StartExecutionOperation fails on node 1 for some of the jobs as is seen above 

We're using **Hazelcast Jet 0.7.2**. Upgrading to a newer version is not an option for us at the moment. Is there any chance to have the behaviour fixed in 0.7.x? Fault tolerance is one of our main reasons for using Hazelcast.

**Comment by viliam-durina** [comment] 2019-08-26 14:38
This was fixed in #1377 and released as part of Jet 3.1. We provide open-source support only for the latest version. The incompatible changes from 0.7.2 were mostly renaming or changing packages and API cleanup, it should be possible for you to upgrade.

**Comment by viliam-durina** [comment] 2019-08-26 14:40
This might help too in migration: https://docs.hazelcast.org/docs/jet/release-notes/index.html#breaking-changes-2

**Comment by cangencer** [comment] 2019-08-26 14:45
@martinkrc could you open a support ticket, if you are a paying customer? We'll see what we can do in terms of providing a patched version for 0.7.2. It would be even better if you could upgrade to 3.1.

**Comment by martinkrc** [comment] 2019-08-28 13:35
Hi, thanks a lot for the brisk answers! We are a paying customer, it's just not clear at the moment how much risk is linked with the upgrade. We've tried to do an experimental upgrade, managed to compile the application (after a series of changes), but now experiencing issues when running. The jobs fail to restart when a new node joins the cluster. 

We see these log entries in node 1:
2019-08-28 14:57:37.445  INFO 12608 --- [cached.thread-6] com.hazelcast.jet.impl.MasterJobContext    : [localhost]:6701 [Application] [3.1] Requested restart of job 'streamingJob', execution 35b4-683e-c686-b985 to make use of added member(s). Job was running on 1 members, cluster now has 2 data members with assigned partitions

I see threads stuck at doing this:
"hz._hzInstance_1_Application.async.thread-4@11893" prio=5 tid=0x67 nid=NA waiting
  java.lang.Thread.State: WAITING
	  at java.lang.Object.wait(Object.java:-1)
	  at com.hazelcast.spi.impl.AbstractCompletableFuture.get(AbstractCompletableFuture.java:229)
	  at com.hazelcast.spi.impl.AbstractCompletableFuture.get(AbstractCompletableFuture.java:191)
	  at com.hazelcast.spi.impl.operationservice.impl.InvokeOnPartitions.invoke(InvokeOnPartitions.java:88)
	  at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.invokeOnAllPartitions(OperationServiceImpl.java:385)
	  at com.hazelcast.map.impl.proxy.MapProxySupport.clearInternal(MapProxySupport.java:1021)
	  at com.hazelcast.map.impl.proxy.MapProxyImpl.clearInternal(MapProxyImpl.java:109)
	  at com.hazelcast.map.impl.proxy.MapProxyImpl.clear(MapProxyImpl.java:698)
	  at com.hazelcast.jet.impl.JobRepository.clearSnapshotData(JobRepository.java:431)
	  at com.hazelcast.jet.impl.MasterJobContext.tryStartJob(MasterJobContext.java:176)
	  at com.hazelcast.jet.impl.JobCoordinationService.tryStartJob(JobCoordinationService.java:800)
	  at com.hazelcast.jet.impl.JobCoordinationService.restartJob(JobCoordinationService.java:647)

We'll try to investigate if time permits, but in case you were aware of the cause, please don't hesitate to let me know. Thanks.

**Comment by viliam-durina** [comment] 2019-08-28 14:46
@martinkrc We're trying to reproduce your issue, could you share the full stack trace where the threads are stuck? Ideally also full thread dump, you can attach it as a file.

**Comment by martinkrc** [comment] 2019-08-28 14:55
Threaddumps here.

[threaddump-node-1.txt](https://github.com/hazelcast/hazelcast-jet/files/3551513/threaddump-node-1.txt)
[threaddump-node-2.txt](https://github.com/hazelcast/hazelcast-jet/files/3551515/threaddump-node-2.txt)

**Comment by viliam-durina** [comment] 2019-08-28 15:33
@martinkrc we have reproduced the issue and have a fix. We're still investigating multiple paths that could lead to this issue. It's related to restarting of many jobs at once (due to the upscaling) and there's a deadlock: a thread is blocking for an operation to complete, but that operation needs a thread from the same pool to complete.

**Comment by martinkrc** [comment] 2019-08-30 07:38
Hi,
Is there an ETA for the release of the fix?

**Comment by viliam-durina** [comment] 2019-08-30 12:20
The fix in the works (#1583). It will be released as part of 3.2. If you need it sooner, raise a support ticket and we can provide a patched 3.1 version for you.

**Comment by viliam-durina** [comment] 2019-08-30 12:21
I expect the issue to be merged on Monday.

**Comment by cangencer** [comment] 2019-08-30 14:27
@martinkrc 3.2 is scheduled for next week or week after. We are in the final stages of wrapping it up.

**Closed** 2019-09-03 08:56 UTC

**Comment by martinkrc** [comment] 2019-09-17 11:48
@cangencer Please please, could you share the release status? We need to know if it makes sense to wait or not.

**Comment by cangencer** [comment] 2019-09-23 08:16
@martinkrc sorry for the delay coming back to you. There's been some delays but we're aiming to release this week and we are in the final stages of QA.

**Comment by viliam-durina** [comment] 2019-09-23 08:19
We don't normally commit to fixed release dates. If there's any issue during the testing, we always decide to postpone the release, unless it's very minor.
