### ISSUE TITLE
 com.hazelcast.jet.impl.execution.WatermarkCoalescer_TerminalSnapshotTest.test

### ISSUE THREAD

**Issue by cangencer** [hazelcast/hazelcast-jet#1112] opened 2018-10-16 19:14 UTC
https://hazelcast-l337.ci.cloudbees.com/view/Jet/job/jet-jdk9/com.hazelcast.jet$hazelcast-jet-core/345/testReport/junit/com.hazelcast.jet.impl.execution/WatermarkCoalescer_TerminalSnapshotTest/test/

```
Error Message
java.lang.IllegalStateException: Cannot RESTART_GRACEFUL, job status is STARTING, should be RUNNING
Stacktrace
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Cannot RESTART_GRACEFUL, job status is STARTING, should be RUNNING
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com.hazelcast.jet.impl.execution.WatermarkCoalescer_TerminalSnapshotTest.test(WatermarkCoalescer_TerminalSnapshotTest.java:136)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
```

**Comment by viliam-durina** [comment] 2018-10-17 07:02
Duplicate of #1095, which was supposed to be fixed

**Closed** 2018-10-18 09:49 UTC
Labels: test-failure
