### ISSUE TITLE
JetClassLoader breaks initialization of javax.xml.parsers.DocumentBuilderFactory

### ISSUE THREAD

**Issue by martinkrc** [hazelcast/hazelcast-jet#1607] opened 2019-09-06 12:15 UTC
(Jet version 0.7.2)

Upon calling javax/xml DocumentBuilderFactory.newInstance(), the JetClassLoader takes into accion somehow and (obviously) interacts with Hazelcast maps which may or may not be available. 

In the following specific example, Hazelcast instance was not active and caused failure of DocumentBuilderFactory.newInstance() invocation, which (I believe) is not acceptable:

Caused by: com.hazelcast.core.HazelcastInstanceNotActiveException: State: SHUT_DOWN Operation: class com.hazelcast.map.impl.operation.ContainsKeyOperation
build	06-Sep-2019 13:44:10		at com.hazelcast.spi.impl.operationservice.impl.Invocation.engineActive(Invocation.java:502)
build	06-Sep-2019 13:44:10		at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:535)
build	06-Sep-2019 13:44:10		at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:525)
build	06-Sep-2019 13:44:10		at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:215)
build	06-Sep-2019 13:44:10		at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.invokeOnPartition(OperationServiceImpl.java:304)
build	06-Sep-2019 13:44:10		at com.hazelcast.map.impl.proxy.MapProxySupport.containsKeyInternal(MapProxySupport.java:621)
build	06-Sep-2019 13:44:10		at com.hazelcast.map.impl.proxy.MapProxyImpl.containsKey(MapProxyImpl.java:237)
build	06-Sep-2019 13:44:10		at com.hazelcast.jet.impl.deployment.JetClassLoader.findResource(JetClassLoader.java:66)
build	06-Sep-2019 13:44:10		at com.hazelcast.jet.impl.deployment.JetClassLoader.findResources(JetClassLoader.java:80)
build	06-Sep-2019 13:44:10		at java.lang.ClassLoader.getResources(ClassLoader.java:1142)
build	06-Sep-2019 13:44:10		at java.util.ServiceLoader$LazyIterator.hasNextService(ServiceLoader.java:348)
build	06-Sep-2019 13:44:10		at java.util.ServiceLoader$LazyIterator.hasNext(ServiceLoader.java:393)
build	06-Sep-2019 13:44:10		at java.util.ServiceLoader$1.hasNext(ServiceLoader.java:474)
build	06-Sep-2019 13:44:10		at javax.xml.parsers.FactoryFinder$1.run(FactoryFinder.java:293)
build	06-Sep-2019 13:44:10		at java.security.AccessController.doPrivileged(Native Method)
build	06-Sep-2019 13:44:10		at javax.xml.parsers.FactoryFinder.findServiceProvider(FactoryFinder.java:289)
build	06-Sep-2019 13:44:10		at javax.xml.parsers.FactoryFinder.find(FactoryFinder.java:267)
build	06-Sep-2019 13:44:10		at javax.xml.parsers.DocumentBuilderFactory.newInstance(DocumentBuilderFactory.java:120)
build	06-Sep-2019 13:44:10		at our.SoapDecoder.lambda$new$0(SoapDecoder.java:39)
build	06-Sep-2019 13:44:10		at java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:284)
build	06-Sep-2019 13:44:10		at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:180)
build	06-Sep-2019 13:44:10		at java.lang.ThreadLocal.get(ThreadLocal.java:170)
build	06-Sep-2019 13:44:10		at our.SoapDecoder.decodeDataBuffer(SoapDecoder.java:69)
build	06-Sep-2019 13:44:10		at our.SoapDecoder.decodeDataBuffer(SoapDecoder.java:30)
build	06-Sep-2019 13:44:10		at org.springframework.core.codec.AbstractDataBufferDecoder.lambda$decodeToMono$1(AbstractDataBufferDecoder.java:68)
build	06-Sep-2019 13:44:10		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:107)
build	06-Sep-2019 13:44:10		at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onNext(FluxContextStart.java:103)
build	06-Sep-2019 13:44:10		at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onNext(FluxMapFuseable.java:287)
build	06-Sep-2019 13:44:10		at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.onNext(FluxFilterFuseable.java:331)
build	06-Sep-2019 13:44:10		at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1510)
build	06-Sep-2019 13:44:10		at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:121)
build	06-Sep-2019 13:44:10		at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136)
build	06-Sep-2019 13:44:10		at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:252)
build	06-Sep-2019 13:44:10		at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:252)
build	06-Sep-2019 13:44:10		at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136)
build	06-Sep-2019 13:44:10		at reactor.netty.channel.FluxReceive.terminateReceiver(FluxReceive.java:390)
build	06-Sep-2019 13:44:10		at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:197)
build	06-Sep-2019 13:44:10		at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:338)
build	06-Sep-2019 13:44:10		at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:350)
build	06-Sep-2019 13:44:10		at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:399)
build	06-Sep-2019 13:44:10		at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:555)
build	06-Sep-2019 13:44:10		at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:91)
build	06-Sep-2019 13:44:10		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
build	06-Sep-2019 13:44:10		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
build	06-Sep-2019 13:44:10		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
build	06-Sep-2019 13:44:10		at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
build	06-Sep-2019 13:44:10		at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
build	06-Sep-2019 13:44:10		at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
build	06-Sep-2019 13:44:10		at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
build	06-Sep-2019 13:44:10		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
build	06-Sep-2019 13:44:10		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
build	06-Sep-2019 13:44:10		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
build	06-Sep-2019 13:44:10		at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
build	06-Sep-2019 13:44:10		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
build	06-Sep-2019 13:44:10		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
build	06-Sep-2019 13:44:10		at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
build	06-Sep-2019 13:44:10		at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
build	06-Sep-2019 13:44:10		at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:682)
build	06-Sep-2019 13:44:10		at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:617)
build	06-Sep-2019 13:44:10		at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:534)
build	06-Sep-2019 13:44:10		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
build	06-Sep-2019 13:44:10		at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
build	06-Sep-2019 13:44:10		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
build	06-Sep-2019 13:44:10		at java.lang.Thread.run(Thread.java:748)
build	06-Sep-2019 13:44:10		at ------ submitted from ------.(Unknown Source)
build	06-Sep-2019 13:44:10		at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:127)
build	06-Sep-2019 13:44:10		at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:79)
build	06-Sep-2019 13:44:10		at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:154)
build	06-Sep-2019 13:44:10		at com.hazelcast.map.impl.proxy.MapProxySupport.containsKeyInternal(MapProxySupport.java:622)
build	06-Sep-2019 13:44:10		at com.hazelcast.map.impl.proxy.MapProxyImpl.containsKey(MapProxyImpl.java:237)
build	06-Sep-2019 13:44:10		at com.hazelcast.jet.impl.deployment.JetClassLoader.findResource(JetClassLoader.java:66)
build	06-Sep-2019 13:44:10		at com.hazelcast.jet.impl.deployment.JetClassLoader.findResources(JetClassLoader.java:80)
build	06-Sep-2019 13:44:10		at java.lang.ClassLoader.getResources(ClassLoader.java:1142)
build	06-Sep-2019 13:44:10		at java.util.ServiceLoader$LazyIterator.hasNextService(ServiceLoader.java:348)
build	06-Sep-2019 13:44:10		at java.util.ServiceLoader$LazyIterator.hasNext(ServiceLoader.java:393)
build	06-Sep-2019 13:44:10		at java.util.ServiceLoader$1.hasNext(ServiceLoader.java:474)
build	06-Sep-2019 13:44:10		at javax.xml.parsers.FactoryFinder$1.run(FactoryFinder.java:293)
build	06-Sep-2019 13:44:10		at java.security.AccessController.doPrivileged(Native Method)
build	06-Sep-2019 13:44:10		at javax.xml.parsers.FactoryFinder.findServiceProvider(FactoryFinder.java:289)
build	06-Sep-2019 13:44:10		at javax.xml.parsers.FactoryFinder.find(FactoryFinder.java:267)
build	06-Sep-2019 13:44:10		at javax.xml.parsers.DocumentBuilderFactory.newInstance(DocumentBuilderFactory.java:120)

**Comment by viliam-durina** [comment] 2019-09-10 09:15
The interesting part of the stack trace is missing. Where was the `DocumentBuilderFactory.newInstance` called? Was it somewhere in the course of a member shutdown?

**Comment by viliam-durina** [comment] 2019-09-10 09:34
Hmm, my previous comment probably isn't related.

It looks like a `DocumentBuilderFactory` instance made it into the `ServiceLoader` list of providers. I'm not familiar with the API, but maybe you supplied an XML parser as job resources (through `JobConfig`), it got used by the job and then the `ServiceLoader` retained the instance after the `JetClassLoader` was released.

The lifecycle of `JetClassLoader` is constrained to the job execution. In 0.7.2 we didn't enforce it and it would access the IMap where we store class bytes after the execution completed (that map is empty at that time). And if the node was shut down, it will fail with your error. In current Jet version we actively check for this and you'll see the job ID the class loader was created for in the error message.

If this is the case, avoid registering the document factory as part of the job. Either use it directly without the service discovery, or add the library to the classpath of the members.

(And maybe I'm totally misled here :)

**Comment by martinkrc** [comment] 2019-09-10 13:21
To be honest, it's not clear to me why DocumentBuilderFactory.newInstance is called in the job context in our case. We're experiencing this situation during some of our JUnit tests and the calling thread is the Spring Webflux nio thread used to decode an HTTP response, so I don't really get why the NIO threads are using JetClassLoader. 

However, my main point was that no matter what, Jet should not break creation of DocumentBuilderFactory. When the application fails to find DocumentBuilderFactory implementation using Hazelcast Jet, it should still fallback to the default one, which is the standard behaviour (see https://docs.oracle.com/javase/7/docs/api/javax/xml/parsers/DocumentBuilderFactory.html#newInstance())

**Comment by viliam-durina** [comment] 2019-09-10 15:03
`DocumentBuilderFactory.newInstance()` isn't called from job context. It's called from `our.SoapDecoder`. But it iterates services in the ServiceLoader and there a service implementation made its way into the `providers` list.

Can you check that you don't ship an XML parser implementation as part of job resources in the same JVM? Or try to reproduce the issue with 3.1, the exception will tell you the jobId which loaded the implementation.

**Comment by cangencer** [comment] 2020-01-20 11:03
@martinkrc is this still an issue for you with 3.2 or can we close it?

**Closed** 2020-02-13 07:52 UTC
