### ISSUE TITLE
Failed to instantiate [com.hazelcast.jet.JetInstance]

### ISSUE THREAD

**Issue by Ultar** [hazelcast/hazelcast-jet#977] opened 2018-07-24 10:43 UTC
When I use an artifact 'hazelcast-jet-spring' with Spring Boot I have this error:

Caused by: java.lang.IllegalArgumentException: DataSerializableFactory[-45] is already registered! com.hazelcast.internal.journal.EventJournalDataSerializerHook$1@67887bf2 -> com.hazelcast.journal.EventJournalDataSerializerHook$1@3ce2c454

**Comment by Ultar** [comment] 2018-07-24 13:43
Thank you for your reply! Yes, I'm using 0.6.1 which has Hazelcast 3.9.4 inside. But I tried to add hazelcast-spring 3.10 instead of main dependency and your advise helped. Thanks!

**Comment by cangencer** [comment] 2018-07-25 08:32
I'm reopening this, because this is caused by `hazelcast-jet-spring` having a dependency to `com.hazelcast:hazelcast` and this causes adding `hazelcast.jar` to classpath. This needs to be fixed on the `hazelcast-jet-spring` pom so that it works out of the box.

**Comment by Ultar** [comment] 2018-07-25 09:14
Ok, I got it.

**Comment by Ultar** [comment] 2018-07-27 08:48
Here is another issue with compatibility of libs above after calling method IMap.put ():

Exception in thread "hz._hzInstance_1_dev.cached.thread-2" java.lang.NoSuchMethodError: com.hazelcast.nio.IOUtil.newObjectInputStream(Ljava/lang/ClassLoader;Ljava/io/InputStream;)Ljava/io/ObjectInputStream;
    at com.hazelcast.jet.impl.execution.init.CustomClassLoadedObject$Serializer.read(CustomClassLoadedObject.java:105)
    at com.hazelcast.jet.impl.execution.init.CustomClassLoadedObject$Serializer.read(CustomClassLoadedObject.java:88)
    at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48)
    at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:269)
    at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:574)
    at com.hazelcast.jet.impl.execution.init.CustomClassLoadedObject.read(CustomClassLoadedObject.java:55)
    at com.hazelcast.jet.core.Vertex.readData(Vertex.java:193)
    at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:160)
    at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:106)
    at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:51)
    at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48)
    at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:269)
    at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:574)
    at com.hazelcast.jet.core.DAG.readData(DAG.java:342)
    at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:160)
    at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:106)
    at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:51)
    at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48)
    at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:187)
    at com.hazelcast.jet.impl.execution.init.CustomClassLoadedObject.deserializeWithCustomClassLoader(CustomClassLoadedObject.java:64)
    at com.hazelcast.jet.impl.MasterContext.deserializeDAG(MasterContext.java:313)
    at com.hazelcast.jet.impl.MasterContext.tryStartJob(MasterContext.java:172)
    at com.hazelcast.jet.impl.JobCoordinationService.tryStartJob(JobCoordinationService.java:273)
    at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitOrJoinJob$1(JobCoordinationService.java:197)
    at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:227)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
    at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
    at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)

**Comment by cangencer** [comment] 2018-07-27 09:09
Could you give more details about in what context this happens please? Looks you have two different versions in your classpath.

**Closed** 2018-08-15 06:28 UTC
Labels: defect, spring
