### ISSUE TITLE
com.hazelcast.jet.core.JobRestartStressTest.stressTest_suspendAndResume

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast-jet#2369] opened 2020-06-26 05:04 UTC
_master_ (commit 8c2716c7b4c6c6d1cf8f7a226e6f2fe1c79ebaed)

Failed on IBM JDK 8: http://jenkins.hazelcast.com/job/jet-oss-master-ibm-jdk8/221/testReport/junit/com.hazelcast.jet.core/JobRestartStressTest/stressTest_suspendAndResume/

Stacktrace:
```
java.util.concurrent.ExecutionException: java.lang.AssertionError: No more snapshots produced after restart in 5 seconds
	at java.util.concurrent.FutureTask.report(FutureTask.java:133)
	at java.util.concurrent.FutureTask.get(FutureTask.java:203)
	at com.hazelcast.jet.core.JobRestartStressTestBase.stressTest(JobRestartStressTestBase.java:73)
	at com.hazelcast.jet.core.JobRestartStressTest.stressTest_suspendAndResume(JobRestartStressTest.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:62)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.AssertionError: No more snapshots produced after restart in 5 seconds
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.jet.core.JetTestSupport.lambda$waitForNextSnapshot$4(JetTestSupport.java:268)
	at com.hazelcast.jet.core.JetTestSupport$$Lambda$2696.00000000E4009B60.run(Unknown Source)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1356)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1373)
	at com.hazelcast.jet.core.JetTestSupport.waitForNextSnapshot(JetTestSupport.java:264)
	at com.hazelcast.jet.core.JobRestartStressTestBase.lambda$stressTest$0(JobRestartStressTestBase.java:70)
	at com.hazelcast.jet.core.JobRestartStressTestBase$$Lambda$2693.00000000885C0E20.call(Unknown Source)
	... 2 more
```

Standard output:
```
Hiccups measured while running test 'stressTest_suspendAndResume(com.hazelcast.jet.core.JobRestartStressTest):'
02:01:00, accumulated pauses: 136 ms, max pause: 11 ms, pauses over 1000 ms: 0
02:01:05, accumulated pauses: 164 ms, max pause: 17 ms, pauses over 1000 ms: 0
02:01:10, accumulated pauses: 51 ms, max pause: 7 ms, pauses over 1000 ms: 0
```

**Comment by viliam-durina** [comment] 2020-06-26 16:43
Relevant logs:
```
2020-06-26 02:01:06,456 [DEBUG] [hz.inspiring_chebyshev.generic-operation.thread-14] [c.h.j.i.o.InitExecutionOperation]: [127.0.0.1]:5702 [jet] [4.2-SNAPSHOT] Initializing execution plan for job 048f-d5b3-c300-0001, execution 048f-d5b3-c302-0001 from [127.0.0.1]:5701
2020-06-26 02:01:06,457 [DEBUG] [hz.kind_chebyshev.cached.thread-5] [c.h.j.i.o.InitExecutionOperation]: [127.0.0.1]:5701 [jet] [4.2-SNAPSHOT] Initializing execution plan for job 048f-d5b3-c300-0001, execution 048f-d5b3-c302-0001 from [127.0.0.1]:5701
2020-06-26 02:01:06,459 [ INFO] [hz.inspiring_chebyshev.generic-operation.thread-14] [c.h.j.i.JobExecutionService]: [127.0.0.1]:5702 [jet] [4.2-SNAPSHOT] Execution plan for jobId=048f-d5b3-c300-0001, jobName='048f-d5b3-c300-0001', executionId=048f-d5b3-c302-0001 initialized
2020-06-26 02:01:06,460 [ INFO] [hz.kind_chebyshev.cached.thread-5] [c.h.j.i.JobExecutionService]: [127.0.0.1]:5701 [jet] [4.2-SNAPSHOT] Execution plan for jobId=048f-d5b3-c300-0001, jobName='048f-d5b3-c300-0001', executionId=048f-d5b3-c302-0001 initialized
2020-06-26 02:01:06,460 [ INFO] [Thread-155] [c.h.j.c.JobRestartStressTest]: resume() returned
2020-06-26 02:01:06,460 [DEBUG] [hz.kind_chebyshev.cached.thread-5] [c.h.j.i.MasterJobContext]: [127.0.0.1]:5701 [jet] [4.2-SNAPSHOT] Init of job '048f-d5b3-c300-0001', execution 048f-d5b3-c302-0001 was successful
2020-06-26 02:01:06,460 [DEBUG] [hz.kind_chebyshev.cached.thread-5] [c.h.j.i.MasterJobContext]: [127.0.0.1]:5701 [jet] [4.2-SNAPSHOT] Executing job '048f-d5b3-c300-0001', execution 048f-d5b3-c302-0001
2020-06-26 02:01:06,460 [ INFO] [hz.kind_chebyshev.cached.thread-5] [c.h.j.i.JobExecutionService]: [127.0.0.1]:5701 [jet] [4.2-SNAPSHOT] Start execution of job '048f-d5b3-c300-0001', execution 048f-d5b3-c302-0001 from coordinator [127.0.0.1]:5701
2020-06-26 02:01:06,460 [ INFO] [hz.inspiring_chebyshev.generic-operation.thread-15] [c.h.j.i.JobExecutionService]: [127.0.0.1]:5702 [jet] [4.2-SNAPSHOT] Start execution of job '048f-d5b3-c300-0001', execution 048f-d5b3-c302-0001 from coordinator [127.0.0.1]:5701
2020-06-26 02:01:06,461 [DEBUG] [hz.kind_chebyshev.cached.thread-5] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [jet] [4.2-SNAPSHOT] job '048f-d5b3-c300-0001', execution 048f-d5b3-c302-0001 snapshot is scheduled in 10ms
2020-06-26 02:01:06,474 [DEBUG] [hz.kind_chebyshev.cached.thread-7] [c.h.j.i.MasterSnapshotContext]: [127.0.0.1]:5701 [jet] [4.2-SNAPSHOT] Starting snapshot 8 for job '048f-d5b3-c300-0001', execution 048f-d5b3-c302-0001, flags: terminal=no,export=no, writing to: null
2020-06-26 02:01:06,474 [DEBUG] [hz.kind_chebyshev.cached.thread-7] [c.h.j.i.e.ExecutionContext]: [127.0.0.1]:5701 [jet] [4.2-SNAPSHOT] Starting snapshot 8 phase 1 for job '048f-d5b3-c300-0001', execution 048f-d5b3-c302-0001 on member
2020-06-26 02:01:06,474 [DEBUG] [hz.inspiring_chebyshev.generic-operation.thread-17] [c.h.j.i.e.ExecutionContext]: [127.0.0.1]:5702 [jet] [4.2-SNAPSHOT] Starting snapshot 8 phase 1 for job '048f-d5b3-c300-0001', execution 048f-d5b3-c302-0001 on member
2020-06-26 02:01:11,677 [ INFO] [Thread-156] [c.h.c.LifecycleService]: [127.0.0.1]:5702 [jet] [4.2-SNAPSHOT] [127.0.0.1]:5702 is SHUTTING_DOWN
```

After the first suspend-resume cycle the execution started normally. First snapshot was scheduled in 10 ms. It fired. Both member logged "Starting snapshot 8 .. on member". And then nothing else is logged for 5 seconds, after which the members were shut down because the test waits for 5 seconds for the snapshot.

The issue likely isn't a test issue. Unfortunately, the test lacked `HazelcastSerialClassRunner` so the thread dump at the time of failure isn't logged.

I didn't try to reproduce it, the test is very old and didn't fail before. Without a reproducer I'm unable to tell the cause. Very interesting is that the operation failed on both members.

**Comment by viliam-durina** [comment] 2020-11-30 15:21
No new occurrence for 5 months, no other occurrence before that, closing.

**Closed by viliam-durina** 2020-11-30 15:21 UTC
Labels: test-failure
