### ISSUE TITLE
 com.hazelcast.jet.core.PostponedSnapshotTest.when_jobHasHigherPriorityEdge_then_noSnapshotUntilEdgeDone

### ISSUE THREAD

**Issue by cangencer** [hazelcast/hazelcast-jet#1123] opened 2018-10-26 10:23 UTC
https://hazelcast-l337.ci.cloudbees.com/job/jet-sonar/com.hazelcast.jet$hazelcast-jet-core/1545/testReport/junit/com.hazelcast.jet.core/PostponedSnapshotTest/when_jobHasHigherPriorityEdge_then_noSnapshotUntilEdgeDone/

```
Stacktrace
java.lang.NullPointerException
	at com.hazelcast.jet.core.PostponedSnapshotTest.lambda$startJob$4(PostponedSnapshotTest.java:99)
	at com.hazelcast.jet.core.JetTestSupport$1.run(JetTestSupport.java:168)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1294)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1311)
	at com.hazelcast.jet.core.JetTestSupport.assertTrueEventually(JetTestSupport.java:133)
	at com.hazelcast.jet.core.PostponedSnapshotTest.startJob(PostponedSnapshotTest.java:99)
	at com.hazelcast.jet.core.PostponedSnapshotTest.when_jobHasHigherPriorityEdge_then_noSnapshotUntilEdgeDone(PostponedSnapshotTest.java:55)
```

**Comment by viliam-durina** [comment] 2018-12-17 13:53
Duplicate of #1134

**Closed by viliam-durina** 2018-12-17 13:53 UTC
Labels: test-failure
