### ISSUE TITLE
Tests are failing on master

### ISSUE THREAD

**Issue by alpert** [hazelcast/hazelcast-jet#1074] opened 2018-09-26 13:53 UTC
When I clone project and run "mvn clean install" tests are failing with the following errors: 

```
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /Users/alpert/code/alpert-hazelcast-jet/hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/util/ExceptionUtilTest.java:[35,1] cannot find symbol
  symbol:   static containsString
  location: class
[ERROR] /Users/alpert/code/alpert-hazelcast-jet/hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/DAGTest.java:[37,1] cannot find symbol
  symbol:   static containsString
  location: class
[ERROR] /Users/alpert/code/alpert-hazelcast-jet/hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/DAGTest.java:[371,41] cannot find symbol
  symbol:   method containsString(java.lang.String)
  location: class com.hazelcast.jet.core.DAGTest
[ERROR] /Users/alpert/code/alpert-hazelcast-jet/hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/util/AsyncSnapshotWriterImplTest.java:[237,75] cannot find symbol
  symbol:   method containsString(java.lang.String)
  location: class org.hamcrest.CoreMatchers
[ERROR] /Users/alpert/code/alpert-hazelcast-jet/hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/util/ExceptionUtilTest.java:[80,43] cannot find symbol
  symbol:   method containsString(java.lang.String)
  location: class com.hazelcast.jet.impl.util.ExceptionUtilTest
[ERROR] /Users/alpert/code/alpert-hazelcast-jet/hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/util/ExceptionUtilTest.java:[98,43] cannot find symbol
  symbol:   method containsString(java.lang.String)
  location: class com.hazelcast.jet.impl.util.ExceptionUtilTest
[INFO] 6 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] hazelcast-jet-root 0.7-SNAPSHOT .................... SUCCESS [  5.856 s]
[INFO] hazelcast-jet-client-protocol ...................... SUCCESS [ 13.430 s]
[INFO] hazelcast-jet-core ................................. FAILURE [ 53.611 s]
[INFO] hazelcast-jet-all .................................. SKIPPED
[INFO] hazelcast-jet-avro ................................. SKIPPED
[INFO] hazelcast-jet-hadoop ............................... SKIPPED
[INFO] hazelcast-jet-kafka ................................ SKIPPED
[INFO] hazelcast-jet-spring ............................... SKIPPED
[INFO] hazelcast-jet-distribution 0.7-SNAPSHOT ............ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:13 min
[INFO] Finished at: 2018-09-26T16:51:10+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:testCompile (default-testCompile) on project hazelcast-jet-core: Compilation failure: Compilation failure:
[ERROR] /Users/alpert/code/alpert-hazelcast-jet/hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/util/ExceptionUtilTest.java:[35,1] cannot find symbol
[ERROR]   symbol:   static containsString
[ERROR]   location: class
[ERROR] /Users/alpert/code/alpert-hazelcast-jet/hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/DAGTest.java:[37,1] cannot find symbol
[ERROR]   symbol:   static containsString
[ERROR]   location: class
[ERROR] /Users/alpert/code/alpert-hazelcast-jet/hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/DAGTest.java:[371,41] cannot find symbol
[ERROR]   symbol:   method containsString(java.lang.String)
[ERROR]   location: class com.hazelcast.jet.core.DAGTest
[ERROR] /Users/alpert/code/alpert-hazelcast-jet/hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/util/AsyncSnapshotWriterImplTest.java:[237,75] cannot find symbol
[ERROR]   symbol:   method containsString(java.lang.String)
[ERROR]   location: class org.hamcrest.CoreMatchers
[ERROR] /Users/alpert/code/alpert-hazelcast-jet/hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/util/ExceptionUtilTest.java:[80,43] cannot find symbol
[ERROR]   symbol:   method containsString(java.lang.String)
[ERROR]   location: class com.hazelcast.jet.impl.util.ExceptionUtilTest
[ERROR] /Users/alpert/code/alpert-hazelcast-jet/hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/util/ExceptionUtilTest.java:[98,43] cannot find symbol
[ERROR]   symbol:   method containsString(java.lang.String)
[ERROR]   location: class com.hazelcast.jet.impl.util.ExceptionUtilTest
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :hazelcast-jet-core
```

**Comment by alpert** [comment] 2018-09-26 13:56
I am working on MacBook Pro (Retina, 13-inch, Early 2015) 2,7 GHz Intel Core i5

Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T21:33:14+03:00)
Maven home: /usr/local/Cellar/maven/3.5.4/libexec
Java version: 1.8.0_111, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.6", arch: "x86_64", family: "mac"

**Comment by cangencer** [comment] 2018-09-27 12:28
Interestingly I couldn't reproduce this problem. Not sure why/how would Mockito cause it?

**Comment by alpert** [comment] 2018-09-27 12:41
I can reproduce it even after deleting my local maven repository under "~/.m2/repository". mockito-all comes with it is own hamcrest package. So I thought separating them will prevent inconsistencies.

**Comment by viliam-durina** [comment] 2018-12-17 14:11
Closing the issue, if you have more information, feel free to reopen it.

**Closed by viliam-durina** 2018-12-17 14:11 UTC
