### ISSUE TITLE
Add check if vertex already exists

### ISSUE THREAD

**Issue by TomaszGaweda** [hazelcast/hazelcast-jet#1221] opened 2019-01-30 13:13 UTC
Hi,

Yesterday I've run into strange error: I've received NullPointerException from Planner.addEdges. After some debugging (issue was not obvious), I've managed to see, that one of components that were creating branches in pipeline tried to add source with the same parameter second  time. That causes this error - source node have overriden it's child nodes after adding again and previous child nodes became orphaned.

Investigation of this issue is quite tricky, so I'd be good to have checks in Jet to prevent such mistakes.

**Comment by viliam-durina** [comment] 2019-01-30 15:03
Can you share the Pipeline code that causes this_

**Comment by cangencer** [comment] 2019-01-31 11:34
@TomaszGaweda were you reusing the same Source instance? They're not meant to be re-used. I've created an issue #1226 so this should fail fast.

**Comment by TomaszGaweda** [comment] 2019-01-31 14:14
@cangencer  Not the same is reused, but new one created with the same config. I'm using latest master. Probably fix you are talking about should be enough - it not a bug, but rather fail-fast behaviour in case of user mistake :)

**Comment by viliam-durina** [comment] 2019-02-05 10:45
Again, can you please share the code to reproduce the problem? We can't reproduce it.

**Comment by TomaszGaweda** [comment] 2019-02-05 12:47
@viliam-durina Hi, sorry for the delay! I will try to provide it this week, I've been quite busy and I have to anonimize & minimize pipeline before publishing :)

**Comment by viliam-durina** [comment] 2019-02-12 15:12
Closing as we cannot reproduce the problem. Feel free to reopen once you have the code to reproduce and it's not fixed by #1226

**Closed by viliam-durina** 2019-02-12 15:12 UTC
