### ISSUE TITLE
Issue with Restarted node after submit the new job.

### ISSUE THREAD

**Issue by parthdwe** [hazelcast/hazelcast-jet#667] opened 2018-01-06 13:21 UTC
Scenario:
1.Start the two jet instance.
2.Submit the job in jet cluster.
3.Restart the one node in the cluster.
4.Again submit the new job in cluster (Don't stop the previous submitted job).

After submitting the job Restarted node is showing the below error and the first instance is running perfectly with new submitted job.

Thanks in Advance!

```
java.io.EOFException: Cannot read 8 bytes!
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.checkAvailable(ByteArrayObjectDataInput.java:638)
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readLong(ByteArrayObjectDataInput.java:311)
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readLong(ByteArrayObjectDataInput.java:305)
	at com.hazelcast.jet.impl.Networking.handleFlowControlPacket(Networking.java:143)
	at com.hazelcast.jet.impl.Networking.handle(Networking.java:72)
	at com.hazelcast.jet.impl.JetService.handle(JetService.java:209)
	at com.hazelcast.spi.impl.NodeEngineImpl$1.handle(NodeEngineImpl.java:172)
	at com.hazelcast.spi.impl.PacketDispatcher.handle(PacketDispatcher.java:76)
	at com.hazelcast.nio.tcp.MemberChannelInboundHandler.handlePacket(MemberChannelInboundHandler.java:71)
	at com.hazelcast.nio.tcp.MemberChannelInboundHandler.onRead(MemberChannelInboundHandler.java:54)
	at com.hazelcast.internal.networking.nio.NioChannelReader.handle(NioChannelReader.java:138)
	at com.hazelcast.internal.networking.nio.NioThread.handleSelectionKey(NioThread.java:401)
	at com.hazelcast.internal.networking.nio.NioThread.handleSelectionKeys(NioThread.java:386)
	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:293)
	at com.hazelcast.internal.networking.nio.NioThread.run(NioThread.java:248)  
  ```

**Comment by viliam-durina** [comment] 2018-01-23 09:33
First of all, if one of the member fails, you should not resubmit the job, it will restart automatically (since Jet 0.5). This is the default option, you can turn it off by `JobConfig.setAutoRestartOnMemberFailure(false)`, however it seems it doesnt work currently (see #682).

I couldn't reproduce it now, but to me it seems that it didn't happen after you submitted the second job, but at the time when the second member was shut down: the connection to the other member was just dropped at the specific moment when header of the flow control packet was received, but the rest of the packet wasn't, which produced unexpected EOF.

Does this exception reproduce consistently?

**Comment by parthdwe** [comment] 2018-01-25 06:55
Thanks for your reply!

> Does this exception reproduce consistently?

Yes, Exception reproduce consistently.

This is the line above the Exception i think this will help.

Failed to process:Packet{partitionId=-1, conn=Connection[id=1, /192.168.1.98:60737->/192.168.1.98:5701, endpoint=[192.168.1.98]:5701, alive=true, type=MEMBER], rawFlags=10111, isUrgent=true, packetType=JET, typeSpecificFlags=[isFlowControl=true]}

Let me Know if you required more information for investigation.

**Comment by viliam-durina** [comment] 2018-01-30 08:24
I can't reproduce the problem. I guess you are using Jet 0.5.1. If I do the scenario you described, i get 
```
java.io.IOException: An existing connection was forcibly closed by the remote host
```
and the job is restarted normally. Can you attach whole log output from both members and the client? How do you start and restart the members?

**Comment by viliam-durina** [comment] 2018-02-06 10:57
Closing as not reproducible. If you have more information, feel free to reopen.

**Comment by viliam-durina** [comment] 2018-02-19 08:19
I've reproduced the issue by chance when running one of our samples, we will fix it.

**Closed** 2018-02-19 08:52 UTC
