### ISSUE TITLE
 com.hazelcast.jet.core.ExecutionLifecycleTest.when_pmsGetThrows_then_jobFails

### ISSUE THREAD

**Issue by cangencer** [hazelcast/hazelcast-jet#922] opened 2018-06-13 18:02 UTC
https://hazelcast-l337.ci.cloudbees.com/view/Jet/job/jet/com.hazelcast.jet$hazelcast-jet-core/781/testReport/junit/com.hazelcast.jet.core/ExecutionLifecycleTest/when_pmsGetThrows_then_jobFails/

```
Error Message
expected null, but was:<JobRecord{jobId=1e36-4c0d-9dd3-c24f, creationTime=2018-06-13T18:40:43.157, dagJson={"vertices":[{"name":"faulty","parallelism":4}],"edges":[]}, config=com.hazelcast.jet.config.JobConfig@7f43a0b4, quorumSize=0}>
Stacktrace
java.lang.AssertionError: expected null, but was:<JobRecord{jobId=1e36-4c0d-9dd3-c24f, creationTime=2018-06-13T18:40:43.157, dagJson={"vertices":[{"name":"faulty","parallelism":4}],"edges":[]}, config=com.hazelcast.jet.config.JobConfig@7f43a0b4, quorumSize=0}>
	at com.hazelcast.jet.core.ExecutionLifecycleTest.getJobResult(ExecutionLifecycleTest.java:571)
	at com.hazelcast.jet.core.ExecutionLifecycleTest.assertJobFailed(ExecutionLifecycleTest.java:562)
	at com.hazelcast.jet.core.ExecutionLifecycleTest.when_pmsGetThrows_then_jobFails(ExecutionLifecycleTest.java:170)
```

**Comment by viliam-durina** [comment] 2018-08-17 08:17
Closing it: issue is old, cannot reproduce locally, didn't happen again and the code parts that could cause this were changed a lot since then.

**Closed by viliam-durina** 2018-08-17 08:17 UTC
Labels: test-failure
